# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/missions/wind/index.ipynb.

# %% auto 0
__all__ = ['wi_mfi_h2_ds', 'wi_pm_3dp_ds', 'wi_plsp_3dp_ds', 'wi_elm2_3dp_ds']

# %% ../../nbs/missions/wind/index.ipynb 0
from ..core import Dataset
from ..meta import MissionMeta, MagDataset, TempDataSet
from datetime import timedelta

# %% ../../nbs/missions/wind/index.ipynb 2
wi_mfi_h2_ds = MagDataset(
    name="WI_H2_MFI",
    parameters=["BGSE"],
    ts=timedelta(seconds=1 / 11),
)

wi_pm_3dp_ds = Dataset(
    dataset="WI_PM_3DP",
    parameters=["P_DENS", "P_VELS", "P_TEMP"],  # Proton velocity vector (GSE)
    description="Wind 3dp, PESA LOW 1 spin resolution ion (proton and alpha) moments (computed on spacecraft)",
)

wi_plsp_3dp_ds = TempDataSet(
    dataset="WI_PLSP_3DP",
    parameters=["MOM.P.MAGT3"],  # T_perp = (MAGT3[0] + MAGT3[1])/2
    para_col="proton_MagT3_Z",
    perp_cols=["proton_MagT3_X", "proton_MagT3_Y"],
)

wi_elm2_3dp_ds = TempDataSet(
    dataset="WI_ELM2_3DP",
    parameters=["MAGT3"],
    para_col="electron_MagT3_Para",
    perp_cols=["electron_MagT3_Perp1", "electron_MagT3_Perp2"],
)
