name: space_analysis
channels:
  - conda-forge
dependencies:  
  - python=3.10
  - rich

  - pandas
  - polars
  - pyarrow
  
  - itables

  - jupyter
  - jupyter-cache

  - plasmapy
  - sunpy

  - gdal # used in `planetarypy`

  - pip
  - pip:
    - pipe
    - great_tables
    - humanize
    - pyspedas
    # - pyspedas@git+https://github.com/Beforerr/pyspedas
    # - pytplot-mpl-temp@git+https://github.com/Beforerr/PyTplot@matplotlib-backend
    - scienceplots
    - pycdfpp # fast CDF reader
    - speasy # Python client for Space Physics web services such as CDAWEB or AMDA.
    - planetarypy
    - pooch # A friend to fetch your Python data files
    # - . # current directory
    - pdpipe
