name: space_analysis
channels:
  - conda-forge
dependencies:  
  - python=3.10
  - loguru
  - rich

  - pandas
  - polars
  - pyarrow
  
  - itables

  - pydantic

  - jupyter
  - jupyter-cache
  - fastai::nbdev

  - plasmapy
  - sunpy

  - pdr # [P]lanetary [D]ata [R]eader - A single function to read all Planetary Data System (PDS) data into Python

  - pytables # used in `pyspedas`

  - gdal # used in `planetarypy`

  - pip
  - pip:
    - pipe
    - great_tables
    - humanize
    - pyspedas
    # - pyspedas@git+https://github.com/Beforerr/pyspedas
    # - pytplot-mpl-temp@git+https://github.com/Beforerr/PyTplot@matplotlib-backend
    - scienceplots
    - pycdfpp # fast CDF reader
    - speasy # Python client for Space Physics web services such as CDAWEB or AMDA.
    - planetarypy
    - pooch # A friend to fetch your Python data files
    - . # current directory
    - pdpipe
