[project]
name = "space-analysis.py"
version = "0.1.0"
description = "Python library for data analysis in space physics"
authors = [{name = "Beforerr", email = "zzj956959688@gmail.com"}]
requires-python = ">= 3.10, < 3.12"
dependencies = [
    "pydantic",
    "polars",
    "plasmapy","astropy","sunpy",
    # "planetarypy",
    "loguru", "rich", "humanize",
    "pycdfpp"
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
space_analysis = { path = ".", editable = true }
nbdev = "*"
setuptools = "*"
jupyter-cache = "*"
itables = "*"

pyspedas = "*"
speasy = "*"
pooch = "*"
pipe = "*"
ray = "*"

[tool.pixi.dependencies]
python = "3.11"
ipykernel = "*"
scipy = "*"
cdasws = "*"
pytables = "*" # used in `pyspedas`
pdr = "*" # [P]lanetary [D]ata [R]eader - A single function to read all Planetary Data System (PDS) data into Python
warpx = "*"

[tool.pixi.tasks]
