[project]
name = "space-analysis.py"
dynamic = ["version"]
description = "Python library for data analysis in space physics"
authors = [{ name = "Beforerr", email = "zzj956959688@gmail.com" }]
readme = "README.md"
requires-python = ">= 3.10, < 3.12"
dependencies = [
    "beforerr",
    "pydantic",
    "polars",
    "plasmapy",
    "astropy",
    "sunpy",
    # "planetarypy",
    "loguru",
    "rich",
    "humanize",
    "pycdfpp",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.optional-dependencies]
complete = ["space_analysis[io]"]
io = [
    "pyspedas",
    "speasy",
    "cdasws",
    "pdr",      # [P]lanetary [D]ata [R]eader - A single function to read all Planetary Data System (PDS) data into Python
]
sim = ["warpx"]

[project.urls]
Homepage = "https://beforerr.github.io/space-analysis.py"
Repository = "https://github.com/beforerr/space-analysis.py"

[tool.pdm.version]
source = "scm"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
space_analysis = { path = ".", editable = true, extras = ["io"] }
nbdev = "*"
setuptools = "*"
jupyter-cache = "*"
itables = "*"
great_tables = "*"
pooch = "*"
pipe = "*"
ray = "*"

[tool.pixi.dependencies]
jupyter = "*"
scipy = "*"
netcdf4 = "*"
pytables = "*" # used in `pyspedas`

[tool.pixi.tasks]
