[project]
name = "space-analysis.py"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "Beforerr", email = "zzj956959688@gmail.com"}]
requires-python = ">= 3.10"
dependencies = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
space_analysis = { path = ".", editable = true }
nbdev = "*"
setuptools = "*"

[tool.pixi.dependencies]
ipykernel = "*"

[tool.pixi.tasks]