# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/data_structure/timeseries/10_utils.ipynb.

# %% auto 0
__all__ = ['get_time_resolution']

# %% ../../../nbs/data_structure/timeseries/10_utils.ipynb 0
from xarray import DataArray
import numpy as np
from plum import dispatch

# %% ../../../nbs/data_structure/timeseries/10_utils.ipynb 1
@dispatch
def get_time_resolution(data: list[DataArray], **kwargs):
    return [get_time_resolution(d, **kwargs) for d in data]


@dispatch
def get_time_resolution(data: DataArray, funcs=[np.min, np.median, np.max], unit="s"):  # noqa: F811
    """
    Get the time resolution of the time series data.

    Args:
    data (DataArray): The time series data.

    Returns:
    float: The time resolution of the time series data.
    """
    time = data.time.values
    dt = np.diff(time) / np.timedelta64(1, unit)
    return {f.__name__: f(dt) for f in funcs}
