# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/space-analysis.py',
                'doc_host': 'https://Beforerr.github.io',
                'git_url': 'https://github.com/Beforerr/space-analysis.py',
                'lib_path': 'space_analysis'},
  'syms': { 'space_analysis.core': {'space_analysis.core.foo': ('core.html#foo', 'space_analysis/core.py')},
            'space_analysis.io.cdf': {'space_analysis.io.cdf.cdf2pl': ('io/cdf.html#cdf2pl', 'space_analysis/io/cdf.py')},
            'space_analysis.missions.psp.mag': { 'space_analysis.missions.psp.mag.download_data': ( 'missions/psp/mag.html#download_data',
                                                                                                    'space_analysis/missions/psp/mag.py'),
                                                 'space_analysis.missions.psp.mag.load_data': ( 'missions/psp/mag.html#load_data',
                                                                                                'space_analysis/missions/psp/mag.py')}}}
