# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/space-analysis',
                'doc_host': 'https://Beforerr.github.io',
                'git_url': 'https://github.com/Beforerr/space-analysis',
                'lib_path': 'space_analysis'},
  'syms': {'space_analysis.core': {'space_analysis.core.foo': ('core.html#foo', 'space_analysis/core.py')}}}
