# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/data_structure/00_meta.ipynb.

# %% auto 0
__all__ = ['Meta', 'PlasmaMeta', 'TempMeta']

# %% ../nbs/data_structure/00_meta.ipynb 0
from pydantic.dataclasses import dataclass
from pydantic import ConfigDict

# %% ../nbs/data_structure/00_meta.ipynb 1
@dataclass(config=ConfigDict(extra='allow'))
class Meta:
    dataset: str = None
    parameters: list[str] = None


class PlasmaMeta(Meta):
    # density_param: str = None
    # velocity_param: str = None
    # temperature_param: str = None
    
    density_col: str = None
    velocity_cols: list[str] = None
    speed_col: str = None
    temperature_col: str = None


class TempMeta(Meta):
    para_col: str = None
    perp_cols: list[str] = None
