# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/data_structure/00_meta.ipynb.

# %% auto 0
__all__ = ['MagDataset', 'DensityDataset', 'VelocityDataset', 'TempDataset', 'PlasmaDataset', 'MissionMeta']

# %% ../nbs/data_structure/00_meta.ipynb 0
from .core import Mission, Dataset

# %% ../nbs/data_structure/00_meta.ipynb 1
class MagDataset(Dataset):
    B_cols: list[str] = None


class DensityDataset(Dataset):
    density_col: str = None


class VelocityDataset(Dataset):
    velocity_cols: list[str] = None
    speed_col: str = None


class TempDataset(Dataset):
    temperature_col: str = None
    para_col: str = None
    perp_cols: list[str] = None


class PlasmaDataset(DensityDataset, VelocityDataset, TempDataset):
    pass

# %% ../nbs/data_structure/00_meta.ipynb 2
class MissionMeta(Mission):
    mag_ds: MagDataset
    plasma_ds: PlasmaDataset
    ion_temp_ds: TempDataset
    e_temp_ds: TempDataset
