# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/missions/themis/index.ipynb.

# %% auto 0
__all__ = ['sta_l1_mag_rtn', 'sta_l2_pla']

# %% ../../../nbs/missions/themis/index.ipynb 1
from ...meta import MagDataset, PlasmaDataset

# %% ../../../nbs/missions/themis/index.ipynb 3
sta_l1_mag_rtn = MagDataset(
    dataset="STA_L1_MAG_RTN",
    parameters=["BFIELD"],
)

sta_l2_pla = PlasmaDataset(
    dataset="STA_L2_PLA_1DMAX_1MIN",
    parameters=[
        "proton_number_density",
        # "V_GSM",
        "proton_temperature",
    ],
)
# TODO: is GSM close to RTN coordinates???
