# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/missions/2015_dscovr.ipynb.

# %% auto 0
__all__ = ['faraday_cup', 'mag', 'dscovr', 'MagDataVars', 'PlasmaDataVars']

# %% ../../../nbs/missions/2015_dscovr.ipynb 1
from typing import Literal
from ...core import Instrument, Mission

# %% ../../../nbs/missions/2015_dscovr.ipynb 2
faraday_cup = Instrument(name="Faraday Cup")
mag = Instrument(name="Magnetometer")
dscovr = Mission(name="DSCOVR", instruments=[mag, faraday_cup])

MagDataVars = Literal[
    "B1F1",
    "B1GSE",
    "B1RTN",
]

PlasmaDataVars = Literal[
    "Np",  # Solar Wind Proton Number Density
    "V_GSE",
    "THERMAL_SPD",
    "THERMAL_TEMP",
]
