# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/missions/dscovr/mag.ipynb.

# %% auto 0
__all__ = ["download_data", "load_data"]

# %% ../../../nbs/missions/dscovr/mag.ipynb 1
import polars as pl
from ...io.cdf import cdf2pl
import pyspedas

from functools import partial


# %% ../../../nbs/missions/dscovr/mag.ipynb 2
def download_data(**kwargs):
    return pyspedas.psp.fields(downloadonly=True, **kwargs)


# %% ../../../nbs/missions/dscovr/mag.ipynb 3
def load_data(var_names="psp_fld_l2_mag_RTN", **kwargs):
    files = download_data(**kwargs)
    load_func = partial(cdf2pl, var_names=var_names)

    return pl.concat(load_func(file) for file in files)
