# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/data_structure/tplot/10_utils.ipynb.

# %% auto 0
__all__ = ['get_time_resolution']

# %% ../../../nbs/data_structure/tplot/10_utils.ipynb 0
from . import get_data
from ..ts.utils import get_time_resolution as get_time_resolution_ts

# %% ../../../nbs/data_structure/tplot/10_utils.ipynb 1
def get_time_resolution(tname, **kwargs):
    return get_time_resolution_ts(get_data(tname), **kwargs)
