# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/data_structure/speasy/02_plot.ipynb.

# %% auto 0
__all__ = ['spz_plot']

# %% ../../../nbs/data_structure/speasy/02_plot.ipynb 0
import speasy as spz
from ...utils.speasy import to_dataarrays
from ..ts.plot import tsplot

# %% ../../../nbs/data_structure/speasy/02_plot.ipynb 1
def spz_plot(product, time_range, **kwargs):
    data = spz.get_data(product, time_range, **kwargs)
    das = to_dataarrays(data)
    return tsplot(das)
