# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/data_structure/speasy/10_utils.ipynb.

# %% auto 0
__all__ = ['get_time_resolution']

# %% ../../../nbs/data_structure/speasy/10_utils.ipynb 0
import speasy as spz
from plum import dispatch

from speasy import SpeasyVariable
from ..ts.utils import get_time_resolution as get_time_resolution_ts

# %% ../../../nbs/data_structure/speasy/10_utils.ipynb 1
@dispatch
def get_time_resolution(data: SpeasyVariable):
    return get_time_resolution_ts(data.time)


@dispatch
def get_time_resolution(product: str, *args, **kwargs):  # noqa: F811
    return get_time_resolution(spz.get_data(product, *args, **kwargs))


@dispatch
def get_time_resolution(products: list[str], *args, **kwargs):  # noqa: F811
    return [get_time_resolution(product, *args, **kwargs) for product in products]
