# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/missions/themis/index.ipynb.

# %% auto 0
__all__ = ['thb_l2_fgm', 'thb_l2_mom', 'thb_l2_mom_ion_temp', 'thb_l2_mom_e_temp']

# %% ../../../nbs/missions/themis/index.ipynb 1
from ...meta import MagDataset, PlasmaDataset, TempDataset

# %% ../../../nbs/missions/themis/index.ipynb 3
thb_l2_fgm = MagDataset(dataset="THB_L2_FGM", parameters=["thb_fgl_gse"])

thb_l2_mom = PlasmaDataset(
    dataset="THB_L2_MOM",
    parameters=[
        "thb_peim_densityQ",
        "thb_peim_velocity_gseQ",
        "thb_peim_ptotQ",
    ],
)

thb_l2_mom_ion_temp = TempDataset(
    dataset="THB_L2_MOM",
    parameters=[
        "thb_peim_t3_magQ",  # (TprpFA1, TprpFA2, TparFA)
        # "thb_peim_ptens_magQ"
    ],
    para_col="Tz_ion FA MOM ESA-B",
    perp_cols=["Tx_ion FA MOM ESA-B", "Ty_ion FA MOM ESA-B"],
)

thb_l2_mom_e_temp = TempDataset(
    dataset="THB_L2_MOM",
    parameters=[
        "thb_peem_t3_magQ",
    ],
    para_col="Tz_elec FA MOM ESA-B",
    perp_cols=["Tx_elec FA MOM ESA-B", "Ty_elec FA MOM ESA-B"],
)
