project:
  type: website
  preview: 
    port: 5557

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    contents: auto

metadata-files: [nbdev.yml]