project:
  type: website
  preview: 
    port: 5557

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [source, issue]
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.ipynb
    tools:
      - icon: github
        href: https://github.com/Beforerr/space-analysis.py
    
  sidebar:
    contents: auto

metadata-files: [nbdev.yml]

execute: 
  cache: true