name: Publishing (GitHub Pages and PyPI)

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  deploy:
    uses: Beforerr/workflows/.github/workflows/pixi_nbdev.yml@main
    secrets: inherit
    permissions: { contents: write }
  pypi-publish:
    uses: Beforerr/workflows/.github/workflows/pypi_publish.yml@main
    permissions:
      id-token: write
      contents: write
