name: Publishing (GitHub Pages and PyPI)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    uses: Beforerr/workflows/.github/workflows/pixi_nbdev.yml@main
    secrets: inherit
    permissions: { contents: write }
  pypi-publish:
    uses: Beforerr/workflows/.github/workflows/pypi_publish.yml@main
    permissions:
      id-token: write
      contents: read