on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  deploy:
    uses: Beforerr/workflows/.github/workflows/pixi_nbdev.yml@main
    secrets: inherit
    permissions: { contents: write }
