on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: Beforerr/workflows/pixi_nbdev@main
